#!/usr/bin/env python3

import subprocess
import shlex

def main():
	list = open("testlist")
	for test in list:
		test = test.split("#")[0]
		if test == "":
			continue
		subprocess.call(["make", "-C", *shlex.split(test), "clean"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
