#!/usr/bin/env python3

import subprocess
import sys

list = open("testlist")

all_passed = True

for testname in list:
	testname = testname.strip()
	sys.stdout.write("Running test {:<30}".format(testname))
	sys.stdout.flush()
	output = subprocess.check_output(["make", "-C", testname, "sim"], stderr=subprocess.STDOUT)
	if "Test PASSED" in output.decode("utf-8"):
		print("[PASSED]")
	else:
		print("[FAILED]")
		all_passed = False
	subprocess.call(["make", "-C", testname, "clean"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

if all_passed:
	print("All tests passed.")
else:
	print("Some tests failed. Re-run failed tests to view output.")