#!/usr/bin/env python3

import subprocess
import sys

list = open("testlist")

all_passed = True

for testname in list:
	testname = testname.strip()
	sys.stdout.write("Running test {:<30}".format(testname))
	sys.stdout.flush()
	try:
		output = subprocess.check_output(["make", "-C", testname, "test"], stderr=subprocess.STDOUT)
	except subprocess.CalledProcessError as e:
		print("\033[33m[ABORT!]\033[39m")
		all_passed = False
	else:
		if "Test PASSED" in output.decode("utf-8"):
			print("\033[32m[PASSED]\033[39m")
		else:
			print("\033[31m[FAILED]\033[39m")
			all_passed = False
	subprocess.call(["make", "-C", testname, "clean"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

if all_passed:
	print("All tests passed.")
else:
	print("Some tests failed. Re-run failed tests to view output.")
