file riscboy_ppu.v
file riscboy_ppu_background.v
file riscboy_ppu_blender.v
file riscboy_ppu_busmaster.v
file riscboy_ppu_dispctrl.v
file riscboy_ppu_pixel_gearbox.v
file riscboy_ppu_raster_counter.v
file regs/ppu_regs.v
include .
list $HDL/common/cdc/async_fifo.f
file $HDL/common/onehot_mux.v
file $HDL/common/onehot_priority.v
file $HDL/common/onehot_encoder.v
file $HDL/common/onehot_priority_dynamic.v
