SRCS=$(HDL)/proc/revive_cpu.v $(HDL)/proc/revive_alu.v $(HDL)/proc/revive_instr_decompress.v $(HDL)/proc/regfile_1w2r.v $(HDL)/mem/ahb_sync_sram.v $(HDL)/mem/sram_sync.v tb.v

include $(SCRIPTS)/sim.mk