
.define image_loc 0x10000
	clip 0 319


	fill 31 0 0
	blit -64   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 320   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -63   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 319   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -62   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 318   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -61   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 317   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -60   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 316   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -59   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 315   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -58   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 314   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -57   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 313   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -56   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 312   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -55   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 311   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -54   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 310   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -53   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 309   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -52   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 308   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -51   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 307   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -50   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 306   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -49   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 305   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -48   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 304   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -47   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 303   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -46   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 302   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -45   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 301   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -44   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 300   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -43   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 299   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -42   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 298   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -41   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 297   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -40   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 296   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -39   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 295   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -38   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 294   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -37   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 293   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -36   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 292   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -35   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 291   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -34   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 290   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -33   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 289   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -32   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 288   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -31   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 287   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -30   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 286   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -29   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 285   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -28   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 284   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -27   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 283   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -26   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 282   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -25   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 281   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -24   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 280   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -23   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 279   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -22   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 278   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -21   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 277   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -20   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 276   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -19   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 275   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -18   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 274   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -17   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 273   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -16   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 272   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -15   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 271   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -14   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 270   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -13   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 269   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -12   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 268   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -11   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 267   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -10   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 266   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -9   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 265   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -8   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 264   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -7   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 263   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -6   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 262   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -5   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 261   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -4   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 260   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -3   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 259   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -2   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 258   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

	fill 31 0 0
	blit -1   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	blit 257   0   size=SIZE_64 img=image_loc fmt=FORMAT_ARGB1555
	sync

loop:
	fill 31 0 0
	sync
	push loop
	popj

