/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _TBMAN_REGS_H_
#define _TBMAN_REGS_H_

// Block name           : tbman
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define TBMAN_PRINT_OFFS 0
#define TBMAN_EXIT_OFFS 4

/*******************************************************************************
*                                    PRINT                                     *
*******************************************************************************/

// Write a byte here to print to sim console

// Field PRINT
#define TBMAN_PRINT_LSB  0
#define TBMAN_PRINT_BITS 8
#define TBMAN_PRINT_MASK 0xff

/*******************************************************************************
*                                     EXIT                                     *
*******************************************************************************/

// Write simulation exit condition here

// Field EXIT
#define TBMAN_EXIT_LSB  0
#define TBMAN_EXIT_BITS 32
#define TBMAN_EXIT_MASK 0xffffffff

#endif // _TBMAN_REGS_H_
