/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _TBMAN_REGS_H_
#define _TBMAN_REGS_H_

// Block name           : tbman
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define TBMAN_PRINT_OFFS 0
#define TBMAN_PUTINT_OFFS 4
#define TBMAN_EXIT_OFFS 8
#define TBMAN_DEFINES_OFFS 12
#define TBMAN_STUB_OFFS 16
#define TBMAN_IRQ_FORCE_OFFS 20

/*******************************************************************************
*                                    PRINT                                     *
*******************************************************************************/

// Write a byte here to print to sim console

// Field: PRINT  Access: WF
#define TBMAN_PRINT_LSB  0
#define TBMAN_PRINT_BITS 8
#define TBMAN_PRINT_MASK 0xff

/*******************************************************************************
*                                    PUTINT                                    *
*******************************************************************************/

// Write a uint32 here to print it (handy for quickly dumping memory etc.)

// Field: PUTINT  Access: WF
#define TBMAN_PUTINT_LSB  0
#define TBMAN_PUTINT_BITS 32
#define TBMAN_PUTINT_MASK 0xffffffff

/*******************************************************************************
*                                     EXIT                                     *
*******************************************************************************/

// Write simulation exit condition here

// Field: EXIT  Access: WF
#define TBMAN_EXIT_LSB  0
#define TBMAN_EXIT_BITS 32
#define TBMAN_EXIT_MASK 0xffffffff

/*******************************************************************************
*                                   DEFINES                                    *
*******************************************************************************/

// The values of some Verilog defines (e.g. whether this is a simulation)

// Field: DEFINES_SIM  Access: ROV
#define TBMAN_DEFINES_SIM_LSB  0
#define TBMAN_DEFINES_SIM_BITS 1
#define TBMAN_DEFINES_SIM_MASK 0x1
// Field: DEFINES_FPGA  Access: ROV
#define TBMAN_DEFINES_FPGA_LSB  1
#define TBMAN_DEFINES_FPGA_BITS 1
#define TBMAN_DEFINES_FPGA_MASK 0x2

/*******************************************************************************
*                                     STUB                                     *
*******************************************************************************/

// Bitmap of devices which have been stubbed out (not present) from this build

// Field: STUB_UART  Access: ROV
#define TBMAN_STUB_UART_LSB  0
#define TBMAN_STUB_UART_BITS 1
#define TBMAN_STUB_UART_MASK 0x1
// Field: STUB_SPI  Access: ROV
#define TBMAN_STUB_SPI_LSB  1
#define TBMAN_STUB_SPI_BITS 1
#define TBMAN_STUB_SPI_MASK 0x2
// Field: STUB_PWM  Access: ROV
#define TBMAN_STUB_PWM_LSB  2
#define TBMAN_STUB_PWM_BITS 1
#define TBMAN_STUB_PWM_MASK 0x4

/*******************************************************************************
*                                  IRQ_FORCE                                   *
*******************************************************************************/

// Force IRQ to be high, at system level

// Field: IRQ_FORCE  Access: RW
#define TBMAN_IRQ_FORCE_LSB  0
#define TBMAN_IRQ_FORCE_BITS 16
#define TBMAN_IRQ_FORCE_MASK 0xffff

#endif // _TBMAN_REGS_H_
