/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

// Block name           : ppu
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

module ppu_regs (
	input wire clk,
	input wire rst_n,
	
	// APB Port
	input wire apbs_psel,
	input wire apbs_penable,
	input wire apbs_pwrite,
	input wire [15:0] apbs_paddr,
	input wire [31:0] apbs_pwdata,
	output wire [31:0] apbs_prdata,
	output wire apbs_pready,
	output wire apbs_pslverr,
	
	// Register interfaces
	output reg  csr_run_o,
	input wire  csr_running_i,
	output reg  csr_halt_vsync_o,
	output reg [8:0] dispsize_w_o,
	output reg [7:0] dispsize_h_o,
	output reg [31:0] cproc_pc_o,
	output reg cproc_pc_wen,
	input wire  ints_vsync_i,
	output reg  ints_vsync_o,
	output reg  inte_vsync_o
);

// APB adapter
wire [31:0] wdata = apbs_pwdata;
reg [31:0] rdata;
wire wen = apbs_psel && apbs_penable && apbs_pwrite;
wire ren = apbs_psel && apbs_penable && !apbs_pwrite;
wire [15:0] addr = apbs_paddr & 16'h1c;
assign apbs_prdata = rdata;
assign apbs_pready = 1'b1;
assign apbs_pslverr = 1'b0;

localparam ADDR_CSR = 0;
localparam ADDR_DISPSIZE = 4;
localparam ADDR_CPROC_PC = 8;
localparam ADDR_INTS = 12;
localparam ADDR_INTE = 16;

wire __csr_wen = wen && addr == ADDR_CSR;
wire __csr_ren = ren && addr == ADDR_CSR;
wire __dispsize_wen = wen && addr == ADDR_DISPSIZE;
wire __dispsize_ren = ren && addr == ADDR_DISPSIZE;
wire __cproc_pc_wen = wen && addr == ADDR_CPROC_PC;
wire __cproc_pc_ren = ren && addr == ADDR_CPROC_PC;
wire __ints_wen = wen && addr == ADDR_INTS;
wire __ints_ren = ren && addr == ADDR_INTS;
wire __inte_wen = wen && addr == ADDR_INTE;
wire __inte_ren = ren && addr == ADDR_INTE;

wire  csr_run_wdata = wdata[0];
wire  csr_run_rdata;
wire  csr_running_wdata = wdata[2];
wire  csr_running_rdata;
wire  csr_halt_vsync_wdata = wdata[4];
wire  csr_halt_vsync_rdata;
wire [31:0] __csr_rdata = {27'h0, csr_halt_vsync_rdata, 1'h0, csr_running_rdata, 1'h0, csr_run_rdata};
assign csr_run_rdata = 1'h0;
assign csr_running_rdata = csr_running_i;
assign csr_halt_vsync_rdata = csr_halt_vsync_o;

wire [8:0] dispsize_w_wdata = wdata[8:0];
wire [8:0] dispsize_w_rdata;
wire [7:0] dispsize_h_wdata = wdata[23:16];
wire [7:0] dispsize_h_rdata;
wire [31:0] __dispsize_rdata = {8'h0, dispsize_h_rdata, 7'h0, dispsize_w_rdata};
assign dispsize_w_rdata = 9'h0;
assign dispsize_h_rdata = 8'h0;

wire [31:0] cproc_pc_wdata = wdata[31:0];
wire [31:0] cproc_pc_rdata;
wire [31:0] __cproc_pc_rdata = {cproc_pc_rdata};
assign cproc_pc_rdata = 32'h0;

wire  ints_vsync_wdata = wdata[0];
wire  ints_vsync_rdata;
wire [31:0] __ints_rdata = {31'h0, ints_vsync_rdata};
reg  ints_vsync;
assign ints_vsync_rdata = ints_vsync;

wire  inte_vsync_wdata = wdata[0];
wire  inte_vsync_rdata;
wire [31:0] __inte_rdata = {31'h0, inte_vsync_rdata};
assign inte_vsync_rdata = inte_vsync_o;

always @ (*) begin
	case (addr)
		ADDR_CSR: rdata = __csr_rdata;
		ADDR_DISPSIZE: rdata = __dispsize_rdata;
		ADDR_CPROC_PC: rdata = __cproc_pc_rdata;
		ADDR_INTS: rdata = __ints_rdata;
		ADDR_INTE: rdata = __inte_rdata;
		default: rdata = 32'h0;
	endcase
	csr_run_o = csr_run_wdata & {1{__csr_wen}};
	cproc_pc_wen = __cproc_pc_wen;
	cproc_pc_o = cproc_pc_wdata;
	ints_vsync_o = ints_vsync;
end

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		csr_halt_vsync_o <= 1'h0;
		dispsize_w_o <= 9'h0;
		dispsize_h_o <= 8'h0;
		ints_vsync <= 1'h0;
		inte_vsync_o <= 1'h0;
	end else begin
		if (__csr_wen)
			csr_halt_vsync_o <= csr_halt_vsync_wdata;
		if (__dispsize_wen)
			dispsize_w_o <= dispsize_w_wdata;
		if (__dispsize_wen)
			dispsize_h_o <= dispsize_h_wdata;
		ints_vsync <= (ints_vsync && !(__ints_wen && ints_vsync_wdata)) || ints_vsync_i;
		if (__inte_wen)
			inte_vsync_o <= inte_vsync_wdata;
	end
end

endmodule
