/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _GPIO_REGS_H_
#define _GPIO_REGS_H_

// Block name           : gpio
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define GPIO_OUT_OFFS 0
#define GPIO_DIR_OFFS 4
#define GPIO_IN_OFFS 8

/*******************************************************************************
*                                     OUT                                      *
*******************************************************************************/

// Processor GPIO pin write register

// Field: OUT  Access: RW
#define GPIO_OUT_LSB  0
#define GPIO_OUT_BITS 11
#define GPIO_OUT_MASK 0x7ff

/*******************************************************************************
*                                     DIR                                      *
*******************************************************************************/

// Processor GPIO output enables

// Field: DIR  Access: RW
#define GPIO_DIR_LSB  0
#define GPIO_DIR_BITS 11
#define GPIO_DIR_MASK 0x7ff

/*******************************************************************************
*                                      IN                                      *
*******************************************************************************/

// Processor GPIO pin read values

// Field: IN  Access: ROV
#define GPIO_IN_LSB  0
#define GPIO_IN_BITS 11
#define GPIO_IN_MASK 0x7ff

#endif // _GPIO_REGS_H_
