file riscboy_fpga_hx8kevn.v
file pll_12_36.v
file pll_12_48.v
file pll_12_30.v
file pll_12_18.v
file $LIBFPGA/common/blinky.v
file $LIBFPGA/common/fpga_reset.v
file $LIBFPGA/common/tristate_io.v
file $LIBFPGA/common/pullup_input.v
list $HDL/riscboy_core/riscboy_core.f
