file riscboy_fpga_icebreaker.v
file pll_12_36.v
file pll_12_30.v
file pll_12_18.v
file $HDL/common/blinky.v
file $HDL/common/fpga_reset.v
file $HDL/common/tristate_io.v
file $HDL/common/pullup_input.v
list $HDL/riscboy_core/riscboy_core.f
