#!/usr/bin/env python3

import sys

f = open(sys.argv[1])
regs = []
found_regs = False
for l in f:
	if found_regs:
		try:
			regs.append(int(l, 16))
		except:
			break
	else:
		found_regs = "Register contents:" in l
assert(len(regs) == 32)

# Actual test:

assert(all(a == b for a, b in zip(regs[8:15],
	[0x1234, 0x56781234, 0xffffff9a, 0x9a, 0x34f09abc, 0xffff9abc, 0x9abc])))
print("Test PASSED.")