# No branches in this test!

	clip 0 319
# Red gradient
	fill r=0
	sync
	fill r=1
	sync
	fill r=2
	sync
	fill r=3
	sync
	fill r=4
	sync
	fill r=5
	sync
	fill r=6
	sync
	fill r=7
	sync
	fill r=8
	sync
	fill r=9
	sync
	fill r=10
	sync
	fill r=11
	sync
	fill r=12
	sync
	fill r=13
	sync
	fill r=14
	sync
	fill r=15
	sync
	fill r=16
	sync
	fill r=17
	sync
	fill r=18
	sync
	fill r=19
	sync
	fill r=20
	sync
	fill r=21
	sync
	fill r=22
	sync
	fill r=23
	sync
	fill r=24
	sync
	fill r=25
	sync
	fill r=26
	sync
	fill r=27
	sync
	fill r=28
	sync
	fill r=29
	sync
	fill r=30
	sync
	fill r=31
	sync
# Green gradient
	fill g=0
	sync
	fill g=1
	sync
	fill g=2
	sync
	fill g=3
	sync
	fill g=4
	sync
	fill g=5
	sync
	fill g=6
	sync
	fill g=7
	sync
	fill g=8
	sync
	fill g=9
	sync
	fill g=10
	sync
	fill g=11
	sync
	fill g=12
	sync
	fill g=13
	sync
	fill g=14
	sync
	fill g=15
	sync
	fill g=16
	sync
	fill g=17
	sync
	fill g=18
	sync
	fill g=19
	sync
	fill g=20
	sync
	fill g=21
	sync
	fill g=22
	sync
	fill g=23
	sync
	fill g=24
	sync
	fill g=25
	sync
	fill g=26
	sync
	fill g=27
	sync
	fill g=28
	sync
	fill g=29
	sync
	fill g=30
	sync
	fill g=31
	sync
# Blue gradient
	fill b=0
	sync
	fill b=1
	sync
	fill b=2
	sync
	fill b=3
	sync
	fill b=4
	sync
	fill b=5
	sync
	fill b=6
	sync
	fill b=7
	sync
	fill b=8
	sync
	fill b=9
	sync
	fill b=10
	sync
	fill b=11
	sync
	fill b=12
	sync
	fill b=13
	sync
	fill b=14
	sync
	fill b=15
	sync
	fill b=16
	sync
	fill b=17
	sync
	fill b=18
	sync
	fill b=19
	sync
	fill b=20
	sync
	fill b=21
	sync
	fill b=22
	sync
	fill b=23
	sync
	fill b=24
	sync
	fill b=25
	sync
	fill b=26
	sync
	fill b=27
	sync
	fill b=28
	sync
	fill b=29
	sync
	fill b=30
	sync
	fill b=31
	sync
# Remainder of frame is cyan
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
	fill 0 31 31
	sync
