/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _SPI_REGS_H_
#define _SPI_REGS_H_

// Block name           : spi
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define SPI_CSR_OFFS 0
#define SPI_DIV_OFFS 4
#define SPI_FSTAT_OFFS 8
#define SPI_TX_OFFS 12
#define SPI_RX_OFFS 16

/*******************************************************************************
*                                     CSR                                      *
*******************************************************************************/

// Control and status register

// Field: CSR_CSAUTO  Access: RW
// If 1, CS pin is driven automatically (low during data transfer, else high)
#define SPI_CSR_CSAUTO_LSB  9
#define SPI_CSR_CSAUTO_BITS 1
#define SPI_CSR_CSAUTO_MASK 0x200
// Field: CSR_CS  Access: RW
// If automatic CS is disabled, use this bit to control CS signal.
#define SPI_CSR_CS_LSB  8
#define SPI_CSR_CS_BITS 1
#define SPI_CSR_CS_MASK 0x100
// Field: CSR_LOOPBACK  Access: RW
// If 1, connect MOSI to MISO internally, for debugging purposes
#define SPI_CSR_LOOPBACK_LSB  5
#define SPI_CSR_LOOPBACK_BITS 1
#define SPI_CSR_LOOPBACK_MASK 0x20
// Field: CSR_READ_EN  Access: RW
// If 0, the received data will not be pushed to RX FIFO. (Transmit only)
#define SPI_CSR_READ_EN_LSB  4
#define SPI_CSR_READ_EN_BITS 1
#define SPI_CSR_READ_EN_MASK 0x10
// Field: CSR_CPOL  Access: RW
// If 0, SCLK low when idle. If 1, high when idle.
#define SPI_CSR_CPOL_LSB  3
#define SPI_CSR_CPOL_BITS 1
#define SPI_CSR_CPOL_MASK 0x8
// Field: CSR_CPHA  Access: RW
// If 0, data captured on leading edge of SCLK pulse. If 1, trailing edge.
#define SPI_CSR_CPHA_LSB  2
#define SPI_CSR_CPHA_BITS 1
#define SPI_CSR_CPHA_MASK 0x4
// Field: CSR_BUSY  Access: ROV
// A transfer is in progress
#define SPI_CSR_BUSY_LSB  0
#define SPI_CSR_BUSY_BITS 1
#define SPI_CSR_BUSY_MASK 0x1

/*******************************************************************************
*                                     DIV                                      *
*******************************************************************************/

// Clock divider register

// Field: DIV  Access: RW
#define SPI_DIV_LSB  0
#define SPI_DIV_BITS 6
#define SPI_DIV_MASK 0x3f

/*******************************************************************************
*                                    FSTAT                                     *
*******************************************************************************/

// FIFO status register

// Field: FSTAT_TXLEVEL  Access: ROV
#define SPI_FSTAT_TXLEVEL_LSB  0
#define SPI_FSTAT_TXLEVEL_BITS 8
#define SPI_FSTAT_TXLEVEL_MASK 0xff
// Field: FSTAT_TXFULL  Access: ROV
#define SPI_FSTAT_TXFULL_LSB  8
#define SPI_FSTAT_TXFULL_BITS 1
#define SPI_FSTAT_TXFULL_MASK 0x100
// Field: FSTAT_TXEMPTY  Access: ROV
#define SPI_FSTAT_TXEMPTY_LSB  9
#define SPI_FSTAT_TXEMPTY_BITS 1
#define SPI_FSTAT_TXEMPTY_MASK 0x200
// Field: FSTAT_TXOVER  Access: W1C
#define SPI_FSTAT_TXOVER_LSB  10
#define SPI_FSTAT_TXOVER_BITS 1
#define SPI_FSTAT_TXOVER_MASK 0x400
// Field: FSTAT_RXLEVEL  Access: ROV
#define SPI_FSTAT_RXLEVEL_LSB  16
#define SPI_FSTAT_RXLEVEL_BITS 8
#define SPI_FSTAT_RXLEVEL_MASK 0xff0000
// Field: FSTAT_RXFULL  Access: ROV
#define SPI_FSTAT_RXFULL_LSB  24
#define SPI_FSTAT_RXFULL_BITS 1
#define SPI_FSTAT_RXFULL_MASK 0x1000000
// Field: FSTAT_RXEMPTY  Access: ROV
#define SPI_FSTAT_RXEMPTY_LSB  25
#define SPI_FSTAT_RXEMPTY_BITS 1
#define SPI_FSTAT_RXEMPTY_MASK 0x2000000
// Field: FSTAT_RXOVER  Access: W1C
#define SPI_FSTAT_RXOVER_LSB  26
#define SPI_FSTAT_RXOVER_BITS 1
#define SPI_FSTAT_RXOVER_MASK 0x4000000
// Field: FSTAT_RXUNDER  Access: W1C
#define SPI_FSTAT_RXUNDER_LSB  27
#define SPI_FSTAT_RXUNDER_BITS 1
#define SPI_FSTAT_RXUNDER_MASK 0x8000000

/*******************************************************************************
*                                      TX                                      *
*******************************************************************************/

// TX data FIFO

// Field: TX  Access: WF
#define SPI_TX_LSB  0
#define SPI_TX_BITS 8
#define SPI_TX_MASK 0xff

/*******************************************************************************
*                                      RX                                      *
*******************************************************************************/

// RX data FIFO

// Field: RX  Access: RF
#define SPI_RX_LSB  0
#define SPI_RX_BITS 8
#define SPI_RX_MASK 0xff

#endif // _SPI_REGS_H_
