#!/usr/bin/env python3

# Script for building Xilinx project files from a list of directory and file paths

import os
import sys

src_files = []
for arg in sys.argv[1:]:
	new_srcs = []
	for root, dir, files in os.walk(arg):
		for file in files:
			if file.endswith(".v"):
				new_srcs.append(os.path.join(root, file))
	if os.path.isfile(arg):
		src_files.append(arg)
	else:
		src_files.extend(new_srcs)

ofile = open("sim.prj", "w")
ofile.write("verilog work {}".format(" ".join(os.path.relpath(file) for file in src_files)))