#SRCS=$(HDL)/busfabric/ahbl_crossbar.v $(HDL)/busfabric/ahbl_arbiter.v $(HDL)/busfabric/ahbl_splitter.v $(HDL)/busfabric/bitmap_mux.v
SRCS=$(HDL)/busfabric/jumplite_switch.v $(HDL)/busfabric/jumplite_torus.v
include $(SCRIPTS)/synth.mk