#!/usr/bin/env python3

import sys

failed = False

tbman_lines = []

for line in open(sys.argv[1]).readlines():
	if line.startswith("TBMAN:"):
		tbman_lines.append(line.strip()[7:])

failed = failed or int(tbman_lines[0], 16) != 3142
failed = failed or int(tbman_lines[1], 16) != 1000
failed = failed or int(tbman_lines[2], 16) != 3
failed = failed or float(tbman_lines[3]) != 3.142
failed = failed or not tbman_lines[4].startswith("CPU requested termination")
failed = failed or tbman_lines[4].split(" ")[-1] != "0"

if not failed:
	print("Test PASSED.")